include("${CMAKE_CURRENT_LIST_DIR}/rule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file.cmake")

set(ble_thread_prov_sed_sensor_default_library_list )

# Handle files with suffix s, for group default-XC32
if(ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_assemble)
add_library(ble_thread_prov_sed_sensor_default_default_XC32_assemble OBJECT ${ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_assemble})
    ble_thread_prov_sed_sensor_default_default_XC32_assemble_rule(ble_thread_prov_sed_sensor_default_default_XC32_assemble)
    list(APPEND ble_thread_prov_sed_sensor_default_library_list "$<TARGET_OBJECTS:ble_thread_prov_sed_sensor_default_default_XC32_assemble>")

endif()

# Handle files with suffix S, for group default-XC32
if(ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_assembleWithPreprocess)
add_library(ble_thread_prov_sed_sensor_default_default_XC32_assembleWithPreprocess OBJECT ${ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_assembleWithPreprocess})
    ble_thread_prov_sed_sensor_default_default_XC32_assembleWithPreprocess_rule(ble_thread_prov_sed_sensor_default_default_XC32_assembleWithPreprocess)
    list(APPEND ble_thread_prov_sed_sensor_default_library_list "$<TARGET_OBJECTS:ble_thread_prov_sed_sensor_default_default_XC32_assembleWithPreprocess>")

endif()

# Handle files with suffix [cC], for group default-XC32
if(ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_compile)
add_library(ble_thread_prov_sed_sensor_default_default_XC32_compile OBJECT ${ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_compile})
    ble_thread_prov_sed_sensor_default_default_XC32_compile_rule(ble_thread_prov_sed_sensor_default_default_XC32_compile)
    list(APPEND ble_thread_prov_sed_sensor_default_library_list "$<TARGET_OBJECTS:ble_thread_prov_sed_sensor_default_default_XC32_compile>")

endif()

# Handle files with suffix cpp, for group default-XC32
if(ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_compile_cpp)
add_library(ble_thread_prov_sed_sensor_default_default_XC32_compile_cpp OBJECT ${ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_compile_cpp})
    ble_thread_prov_sed_sensor_default_default_XC32_compile_cpp_rule(ble_thread_prov_sed_sensor_default_default_XC32_compile_cpp)
    list(APPEND ble_thread_prov_sed_sensor_default_library_list "$<TARGET_OBJECTS:ble_thread_prov_sed_sensor_default_default_XC32_compile_cpp>")

endif()

# Handle files with suffix [cC], for group default-XC32
if(ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_dependentObject)
add_library(ble_thread_prov_sed_sensor_default_default_XC32_dependentObject OBJECT ${ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_dependentObject})
    ble_thread_prov_sed_sensor_default_default_XC32_dependentObject_rule(ble_thread_prov_sed_sensor_default_default_XC32_dependentObject)
    list(APPEND ble_thread_prov_sed_sensor_default_library_list "$<TARGET_OBJECTS:ble_thread_prov_sed_sensor_default_default_XC32_dependentObject>")

endif()

# Handle files with suffix elf, for group default-XC32
if(ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_bin2hex)
add_library(ble_thread_prov_sed_sensor_default_default_XC32_bin2hex OBJECT ${ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_bin2hex})
    ble_thread_prov_sed_sensor_default_default_XC32_bin2hex_rule(ble_thread_prov_sed_sensor_default_default_XC32_bin2hex)
    list(APPEND ble_thread_prov_sed_sensor_default_library_list "$<TARGET_OBJECTS:ble_thread_prov_sed_sensor_default_default_XC32_bin2hex>")

endif()


# Main target for this project
add_executable(ble_thread_prov_sed_sensor_default_image_agqgMInt ${ble_thread_prov_sed_sensor_default_library_list})

set_target_properties(ble_thread_prov_sed_sensor_default_image_agqgMInt PROPERTIES
    OUTPUT_NAME "default"
    SUFFIX ".elf"
    RUNTIME_OUTPUT_DIRECTORY "${ble_thread_prov_sed_sensor_default_output_dir}")
target_link_libraries(ble_thread_prov_sed_sensor_default_image_agqgMInt PRIVATE ${ble_thread_prov_sed_sensor_default_default_XC32_FILE_TYPE_link})

# Add the link options from the rule file.
ble_thread_prov_sed_sensor_default_link_rule( ble_thread_prov_sed_sensor_default_image_agqgMInt)

# Call bin2hex function from the rule file
ble_thread_prov_sed_sensor_default_bin2hex_rule(ble_thread_prov_sed_sensor_default_image_agqgMInt)

