configVersion: 1.0.0
componentName: core
coreVersion: 5.9.1-tc.b
device: PIC32WM_BZ6204
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: core
  type: module
  version: ''
- dependencyPackage: ''
  name: csp
  type: package
  version: v3.25.2
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition: {}
  symbols:
    BLE_CLOCK_ENABLE:
      attributes:
        id: BLE_CLOCK_ENABLE
        label: BLE Clock Enable
      children:
      - children:
        - attributes:
            id: BLE_STACK_LIB
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-1_0_ENABLE:
      attributes:
        id: NVIC_-1_0_ENABLE
        label: Enable System Tick Timer Interrupt
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-1_0_HANDLER:
      attributes:
        id: NVIC_-1_0_HANDLER
        label: Handler
      children:
      - children:
        - attributes:
            id: core
            value: xPortSysTickHandler
          type: Dynamic
        type: Values
      type: String
    NVIC_-1_0_HANDLER_LOCK:
      attributes:
        id: NVIC_-1_0_HANDLER_LOCK
        label: Handler Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-1_0_PRIORITY:
      attributes:
        id: NVIC_-1_0_PRIORITY
        label: Priority
      children:
      - children:
        - attributes:
            id: core
            value: '7'
          type: Dynamic
        type: Values
      type: Combo
    NVIC_-1_0_PRIORITY_LOCK:
      attributes:
        id: NVIC_-1_0_PRIORITY_LOCK
        label: Priority Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-2_0_ENABLE:
      attributes:
        id: NVIC_-2_0_ENABLE
        label: Enable Pendable request for system service Interrupt
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-2_0_HANDLER:
      attributes:
        id: NVIC_-2_0_HANDLER
        label: Handler
      children:
      - children:
        - attributes:
            id: core
            value: xPortPendSVHandler
          type: Dynamic
        type: Values
      type: String
    NVIC_-2_0_HANDLER_LOCK:
      attributes:
        id: NVIC_-2_0_HANDLER_LOCK
        label: Handler Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-5_0_ENABLE:
      attributes:
        id: NVIC_-5_0_ENABLE
        label: Enable System Service Call via SVC instruction Interrupt
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-5_0_HANDLER:
      attributes:
        id: NVIC_-5_0_HANDLER
        label: Handler
      children:
      - children:
        - attributes:
            id: core
            value: vPortSVCHandler
          type: Dynamic
        type: Values
      type: String
    NVIC_-5_0_HANDLER_LOCK:
      attributes:
        id: NVIC_-5_0_HANDLER_LOCK
        label: Handler Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_-5_0_PRIORITY_LOCK:
      attributes:
        id: NVIC_-5_0_PRIORITY_LOCK
        label: Priority Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_3_0_ENABLE:
      attributes:
        id: NVIC_3_0_ENABLE
        label: Enable Non-Volatile Memory Interrupt
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVIC_3_0_HANDLER:
      attributes:
        id: NVIC_3_0_HANDLER
        label: Handler
      children:
      - children:
        - attributes:
            id: core
            value: NVM_InterruptHandler
          type: Dynamic
        type: Values
      type: String
    NVIC_3_0_HANDLER_LOCK:
      attributes:
        id: NVIC_3_0_HANDLER_LOCK
        label: Handler Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVM_INTERRUPT_ENABLE:
      attributes:
        id: NVM_INTERRUPT_ENABLE
        label: Vector Peripheral Enable
      children:
      - children:
        - attributes:
            id: nvm
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    NVM_INTERRUPT_ENABLE_UPDATE:
      attributes:
        id: NVM_INTERRUPT_ENABLE_UPDATE
        label: NVIC Peripheral Enable/Disable Update
      children:
      - children:
        - attributes:
            id: core
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    NVM_INTERRUPT_HANDLER:
      attributes:
        id: NVM_INTERRUPT_HANDLER
        label: Vector Peripheral Handler
      children:
      - children:
        - attributes:
            id: nvm
            value: NVM_InterruptHandler
          type: Dynamic
        type: Values
      type: String
    NVM_INTERRUPT_HANDLER_LOCK:
      attributes:
        id: NVM_INTERRUPT_HANDLER_LOCK
        label: Vector Peripheral Handler Lock
      children:
      - children:
        - attributes:
            id: nvm
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    PendSV_INTERRUPT_ENABLE:
      attributes:
        id: PendSV_INTERRUPT_ENABLE
        label: Vector Peripheral Enable
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    PendSV_INTERRUPT_ENABLE_UPDATE:
      attributes:
        id: PendSV_INTERRUPT_ENABLE_UPDATE
        label: NVIC Peripheral Enable/Disable Update
      children:
      - children:
        - attributes:
            id: core
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    PendSV_INTERRUPT_HANDLER:
      attributes:
        id: PendSV_INTERRUPT_HANDLER
        label: Vector Peripheral Handler
      children:
      - children:
        - attributes:
            id: core
            value: xPortPendSVHandler
          type: Dynamic
        type: Values
      type: String
    PendSV_INTERRUPT_HANDLER_LOCK:
      attributes:
        id: PendSV_INTERRUPT_HANDLER_LOCK
        label: Vector Peripheral Handler Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    SVCall_INTERRUPT_ENABLE:
      attributes:
        id: SVCall_INTERRUPT_ENABLE
        label: Vector Peripheral Enable
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    SVCall_INTERRUPT_ENABLE_UPDATE:
      attributes:
        id: SVCall_INTERRUPT_ENABLE_UPDATE
        label: NVIC Peripheral Enable/Disable Update
      children:
      - children:
        - attributes:
            id: core
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    SVCall_INTERRUPT_HANDLER:
      attributes:
        id: SVCall_INTERRUPT_HANDLER
        label: Vector Peripheral Handler
      children:
      - children:
        - attributes:
            id: core
            value: vPortSVCHandler
          type: Dynamic
        type: Values
      type: String
    SVCall_INTERRUPT_HANDLER_LOCK:
      attributes:
        id: SVCall_INTERRUPT_HANDLER_LOCK
        label: Vector Peripheral Handler Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    SysTick_INTERRUPT_ENABLE:
      attributes:
        id: SysTick_INTERRUPT_ENABLE
        label: Vector Peripheral Enable
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    SysTick_INTERRUPT_ENABLE_UPDATE:
      attributes:
        id: SysTick_INTERRUPT_ENABLE_UPDATE
        label: NVIC Peripheral Enable/Disable Update
      children:
      - children:
        - attributes:
            id: core
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    SysTick_INTERRUPT_HANDLER:
      attributes:
        id: SysTick_INTERRUPT_HANDLER
        label: Vector Peripheral Handler
      children:
      - children:
        - attributes:
            id: core
            value: xPortSysTickHandler
          type: Dynamic
        type: Values
      type: String
    SysTick_INTERRUPT_HANDLER_LOCK:
      attributes:
        id: SysTick_INTERRUPT_HANDLER_LOCK
        label: Vector Peripheral Handler Lock
      children:
      - children:
        - attributes:
            id: core
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    XC32_HEAP_SIZE:
      attributes:
        id: XC32_HEAP_SIZE
        label: Heap Size (bytes)
      children:
      - children:
        - attributes:
            id: core
            value: '1024'
          type: Dynamic
        type: Values
      type: Integer
    ZIGBEE_CLOCK_ENABLE:
      attributes:
        id: ZIGBEE_CLOCK_ENABLE
        label: ZIGBEE Clock Enable
      children:
      - children:
        - attributes:
            id: IEEE_802154_PHY
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
  userData: {}
