configVersion: 1.0.0
componentName: IEEE_802154_PHY
coreVersion: 5.9.1-tc.b
device: PIC32WM_BZ6204
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: IEEE_802154_PHY
  type: module
  version: ''
- dependencyPackage: ''
  name: wireless_15_4_phy
  type: package
  version: v1.4.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition: {}
  symbols:
    APP_TX_POWER:
      attributes:
        id: APP_TX_POWER
        label: Tx Power Set
      type: Integer
    CREATE_PHY_RTOS_TASK:
      attributes:
        id: CREATE_PHY_RTOS_TASK
        label: Create PHY RTOS Task
      type: Boolean
    CREATE_PHY_SEMAPHORE:
      attributes:
        id: CREATE_PHY_SEMAPHORE
        label: Create PHY Semaphore
      type: Boolean
    CUSTOM_ANT_GAIN:
      attributes:
        id: CUSTOM_ANT_GAIN
        label: CUSTOM_ANT_GAIN
      children:
      - children:
        - attributes:
            id: IEEE_802154_PHY
            value: '3'
          type: Dynamic
        type: Values
      type: Integer
    PHY_INTEGER_BMMLARGEBUFFERS:
      attributes:
        id: PHY_INTEGER_BMMLARGEBUFFERS
        label: Large Buffers
      type: Integer
    PHY_INTEGER_BMMSMALLBUFFERS:
      attributes:
        id: PHY_INTEGER_BMMSMALLBUFFERS
        label: Small Buffers
      type: Integer
    PHY_PTA_DEBUG_CONFIG_ENABLE:
      attributes:
        id: PHY_PTA_DEBUG_CONFIG_ENABLE
        label: Debug Info
      type: Boolean
    PHY_PTA_ED_PRIORITY:
      attributes:
        id: PHY_PTA_ED_PRIORITY
        label: ED Priority
      type: Boolean
    PHY_PTA_ENABLE:
      attributes:
        id: PHY_PTA_ENABLE
        label: Enable PTA CoEx
      children:
      - children:
        - attributes:
            id: IEEE_802154_PHY
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    PHY_PTA_INTERFACE:
      attributes:
        id: PHY_PTA_INTERFACE
        label: PTA Interface
      type: KeyValueSet
    PHY_PTA_RX_PRIORITY_LEVEL:
      attributes:
        id: PHY_PTA_RX_PRIORITY_LEVEL
        label: RX Priority Level
      type: KeyValueSet
    PHY_PTA_TX_CCA_PRIORITY_LEVEL:
      attributes:
        id: PHY_PTA_TX_CCA_PRIORITY_LEVEL
        label: CCA Priority Level
      type: KeyValueSet
    PHY_PTA_TX_MAC_RETRY_PRIORITY_LEVEL:
      attributes:
        id: PHY_PTA_TX_MAC_RETRY_PRIORITY_LEVEL
        label: MAC Retry Priority Level
      type: KeyValueSet
    PHY_TASK_PRIORITY:
      attributes:
        id: PHY_TASK_PRIORITY
        label: PHY RTOS Task Priority
      type: Integer
    PIC32CXBZ6:
      attributes:
        id: PIC32CXBZ6
        label: PIC32CXBZ6
      type: Boolean
    TX_PWR_MAX_NON_FHSS:
      attributes:
        id: TX_PWR_MAX_NON_FHSS
        label: TX_PWR_MAX_NON_FHSS
      children:
      - children:
        - attributes:
            id: IEEE_802154_PHY
            value: '10'
          type: Dynamic
        type: Values
      type: Integer
    USE_CUSTOM_ANT_GAIN:
      attributes:
        id: USE_CUSTOM_ANT_GAIN
        label: USE_CUSTOM_ANT_GAIN
      children:
      - children:
        - attributes:
            id: IEEE_802154_PHY
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
  userData: {}
