configVersion: 1.0.0
componentName: nvm
coreVersion: 5.9.1-tc.b
device: PIC32WM_BZ6204
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: nvm
  type: module
  version: ''
- dependencyPackage: ''
  name: csp
  type: package
  version: v3.25.2
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments:
    children:
    - children:
      - attributes:
          id: NVM_MEMORY
        children:
        - children:
          - attributes:
              id: targetComponentID
            children:
            - type: Value
              value: pdsSystem
            type: String
          - attributes:
              id: targetAttachmentID
            children:
            - type: Value
              value: NVM_Dependency
            type: String
          type: Attributes
        type: DirectCapability
      type: Attachments
    type: nvm
  elementPosition: {}
  symbols:
    DRV_MEMORY_CONNECTED:
      attributes:
        id: DRV_MEMORY_CONNECTED
        label: Memory Driver Connected
      type: Boolean
    ERASE_API_NAME:
      attributes:
        id: ERASE_API_NAME
        label: ERASE_API_NAME
      type: String
    ERASE_BUFFER_SIZE:
      attributes:
        id: ERASE_BUFFER_SIZE
        label: NVM Erase Buffer Size
      type: Integer
    ERASE_ENABLE:
      attributes:
        id: ERASE_ENABLE
        label: NVM Erase Enable
      type: Boolean
    FLASH_ERASE_SIZE:
      attributes:
        id: FLASH_ERASE_SIZE
        label: FLASH_ERASE_SIZE
      type: String
    FLASH_PROGRAM_SIZE:
      attributes:
        id: FLASH_PROGRAM_SIZE
        label: FLASH_PROGRAM_SIZE
      type: String
    FLASH_SIZE:
      attributes:
        id: FLASH_SIZE
        label: FLASH_SIZE
      type: String
    FLASH_START_ADDRESS:
      attributes:
        id: FLASH_START_ADDRESS
        label: FLASH_START_ADDRESS
      type: String
    FLASH_WRITE_WORD_SIZE:
      attributes:
        id: FLASH_WRITE_WORD_SIZE
        label: FLASH_WRITE_WORD_SIZE
      type: String
    INTERRUPT_ENABLE:
      attributes:
        id: INTERRUPT_ENABLE
        label: Enable Interrupt?
      type: Boolean
    MEMORY_MEDIA_SIZE:
      attributes:
        id: MEMORY_MEDIA_SIZE
        label: NVM Media Size (KB)
      type: Integer
    NVM_IEC_REG:
      attributes:
        id: NVM_IEC_REG
        label: NVM_IEC_REG
      type: String
    NVM_IEC_REG_VALUE:
      attributes:
        id: NVM_IEC_REG_VALUE
        label: NVM_IEC_REG_VALUE
      type: String
    NVM_IFS_REG:
      attributes:
        id: NVM_IFS_REG
        label: NVM_IFS_REG
      type: String
    NVM_IFS_REG_VALUE:
      attributes:
        id: NVM_IFS_REG_VALUE
        label: NVM_IFS_REG_VALUE
      type: String
    NVM_INSTANCE_NAME:
      attributes:
        id: NVM_INSTANCE_NAME
        label: NVM_INSTANCE_NAME
      type: String
    NVM_VECTOR_NUMBER:
      attributes:
        id: NVM_VECTOR_NUMBER
        label: NVM_VECTOR_NUMBER
      type: Integer
    START_ADDRESS:
      attributes:
        id: START_ADDRESS
        label: NVM Media Start Address
      type: String
    WRITE_API_NAME:
      attributes:
        id: WRITE_API_NAME
        label: WRITE_API_NAME
      type: String
  userData: {}
