configVersion: 1.0.0
componentName: pic32cx_bz6_devsupport
coreVersion: 5.9.1-tc.b
device: PIC32WM_BZ6204
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: pic32cx_bz6_devsupport
  type: module
  version: ''
- dependencyPackage: ''
  name: wireless_pic32cxbz_wbz
  type: package
  version: v1.6.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition: {}
  symbols:
    APP_IDLE_TASK_C:
      attributes:
        id: APP_IDLE_TASK_C
      children:
      - children:
        - attributes:
            id: enabled
          children:
          - type: Value
            value: 'true'
          type: Boolean
        type: Attributes
      type: File
    APP_IDLE_TASK_H:
      attributes:
        id: APP_IDLE_TASK_H
      children:
      - children:
        - attributes:
            id: enabled
          children:
          - type: Value
            value: 'true'
          type: Boolean
        type: Attributes
      type: File
    APP_RETENTION_RAM:
      attributes:
        id: APP_RETENTION_RAM
        label: Application Retention RAM Size (bytes)
      type: Integer
    APP_USER_EDITS_C:
      attributes:
        id: APP_USER_EDITS_C
      children:
      - children:
        - attributes:
            id: enabled
          children:
          - type: Value
            value: 'true'
          type: Boolean
        type: Attributes
      type: File
    AUTO_LOAD_PDS:
      attributes:
        id: AUTO_LOAD_PDS
        label: Auto load PDS_SubSystem
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    BLESTACK_LOADED:
      attributes:
        id: BLESTACK_LOADED
        label: BLESTACK_LOADED
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    BLE_PTA_SUPPORTED:
      attributes:
        id: BLE_PTA_SUPPORTED
        label: PTA Support Required for BLE Stack
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    BLE_SLEEP_SUPPORTED:
      attributes:
        id: BLE_SLEEP_SUPPORTED
        label: Sleep support required by BLE stack
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    CHINA_REGION:
      attributes:
        id: CHINA_REGION
        label: CHINA
      type: Boolean
    CUSTOM_ANT_ENABLE:
      attributes:
        id: CUSTOM_ANT_ENABLE
        label: Enable Custom Antenna Gain
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    CUSTOM_ANT_GAIN:
      attributes:
        id: CUSTOM_ANT_GAIN
        label: Custom Antenna Gain (dBm)
      type: Integer
    DEVICE_CHECON_PFMWS:
      attributes:
        id: DEVICE_CHECON_PFMWS
        label: Program Flash memory Wait states
      type: Integer
    DEVICE_CHECON_PREFEN:
      attributes:
        id: DEVICE_CHECON_PREFEN
        label: Predictive Prefetch Configuration
      type: Integer
    DISABLE_APP_CODE_GEN:
      attributes:
        id: DISABLE_APP_CODE_GEN
        label: Disable App Code Gen
      type: Boolean
    ENABLE_CONSOLE:
      attributes:
        id: ENABLE_CONSOLE
        label: Enable Console
      type: Boolean
    ENABLE_DEEP_SLEEP:
      attributes:
        id: ENABLE_DEEP_SLEEP
        label: Enable Deep Sleep (Retention RAM)
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    ETSI_REGION:
      attributes:
        id: ETSI_REGION
        label: ETSI/UK
      type: Boolean
    FCC_REGION:
      attributes:
        id: FCC_REGION
        label: FCC/IC
      type: Boolean
    FREERTOS_CONFIG_PATH:
      attributes:
        id: FREERTOS_CONFIG_PATH
        label: FREERTOS_CONFIG_PATH
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: config/default/FreeRTOSConfig.h/
          type: Dynamic
        type: Values
      type: String
    IDLE_TASK_CAL:
      attributes:
        id: IDLE_TASK_CAL
        label: Include RF cal in Idle Task
      type: Boolean
    IEEE_802154_PHY_LOADED:
      attributes:
        id: IEEE_802154_PHY_LOADED
        label: IEEE_802154_PHY_LOADED
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    JAPAN_REGION:
      attributes:
        id: JAPAN_REGION
        label: JAPAN
      type: Boolean
    KOREA_REGION:
      attributes:
        id: KOREA_REGION
        label: KOREA
      type: Boolean
    MAC_DEEP_SLEEP_SUPPORTED:
      attributes:
        id: MAC_DEEP_SLEEP_SUPPORTED
        label: Sleep support required by Standlone MAC
      type: Boolean
    OT_DEEP_SLEEP_SUPPORTED:
      attributes:
        id: OT_DEEP_SLEEP_SUPPORTED
        label: Sleep support required by Thread stack
      type: Boolean
    PDS_LOADED:
      attributes:
        id: PDS_LOADED
        label: PDS_LOADED
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    PHY_PTA_SUPPORTED:
      attributes:
        id: PHY_PTA_SUPPORTED
        label: PTA Support Required for 802.15.4 PHY Stack
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    PIC32CX_BZ6_DEVICE:
      attributes:
        id: PIC32CX_BZ6_DEVICE
        label: PIC32CX_BZ6_DEVICE
      type: Boolean
    PIC32WM_BZ6_DEVICE:
      attributes:
        id: PIC32WM_BZ6_DEVICE
        label: PIC32WM_BZ6_DEVICE
      type: Boolean
    PTA_ENABLE:
      attributes:
        id: PTA_ENABLE
        label: Enable PTA CoEx
      type: Boolean
    PTA_INTERFACE:
      attributes:
        id: PTA_INTERFACE
        label: PTA Interface
      type: KeyValueSet
    PTA_PRIORITY_PIN:
      attributes:
        id: PTA_PRIORITY_PIN
        label: PTA_Priority Pin
      type: KeyValueSet
    PTA_REQ_PIN:
      attributes:
        id: PTA_REQ_PIN
        label: PTA_Req Pin
      type: KeyValueSet
    PTA_WLAN_ACTIVE_PIN:
      attributes:
        id: PTA_WLAN_ACTIVE_PIN
        label: WLAN_Active Pin
      type: KeyValueSet
    SLEEP_SUPPORTED:
      attributes:
        id: SLEEP_SUPPORTED
        label: Sleep support required by System
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    STACK_RETENTION_RAM:
      attributes:
        id: STACK_RETENTION_RAM
        label: Stack Retention RAM Size (bytes)
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: '0'
          type: Dynamic
        type: Values
      type: Integer
    SYSTEM_ENABLE_PMUMODE_SETTING:
      attributes:
        id: SYSTEM_ENABLE_PMUMODE_SETTING
        label: Enable PMU Mode Setting
      type: Boolean
    SYSTEM_PMU_MODE:
      attributes:
        id: SYSTEM_PMU_MODE
        label: PMU Mode
      type: Combo
    TAIWAN_REGION:
      attributes:
        id: TAIWAN_REGION
        label: TAIWAN
      type: Boolean
    TOTAL_RETENTION_RAM:
      attributes:
        id: TOTAL_RETENTION_RAM
        label: TOTAL_RETENTION_RAM
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: '1'
          type: Dynamic
        type: Values
      type: Integer
    TOTAL_RETENTION_RAM_BYTES:
      attributes:
        id: TOTAL_RETENTION_RAM_BYTES
        label: TOTAL_RETENTION_RAM_BYTES
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: '0'
          type: Dynamic
        type: Values
      type: Integer
    WSS_ENABLE_MODE:
      attributes:
        id: WSS_ENABLE_MODE
        label: WSS_ENABLE_MODE
      children:
      - children:
        - attributes:
            id: pic32cx_bz6_devsupport
            value: WSS_ENABLE_BLE_ZB
          type: Dynamic
        type: Values
      type: String
    ZB_DEEP_SLEEP_SUPPORTED:
      attributes:
        id: ZB_DEEP_SLEEP_SUPPORTED
        label: Sleep support required by Zigbee stack
      type: Boolean
    ZB_SLEEP_SUPPORTED:
      attributes:
        id: ZB_SLEEP_SUPPORTED
        label: Sleep support required by Zigbee stack
      type: Boolean
  userData: {}
