configVersion: 1.0.0
componentName: SERVICE_TRS
coreVersion: 5.9.1-tc.b
device: PIC32WM_BZ6204
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: SERVICE_TRS
  type: module
  version: ''
- dependencyPackage: ''
  name: wireless_ble
  type: package
  version: v1.5.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments:
    children:
    - children:
      - attributes:
          id: BLE_TRS_Capability
        children:
        - children:
          - attributes:
              id: targetComponentID
            children:
            - type: Value
              value: PROFILE_TRSP
            type: String
          - attributes:
              id: targetAttachmentID
            children:
            - type: Value
              value: BLE_TRS_Dependency
            type: String
          type: Attributes
        type: DirectCapability
      type: Attachments
    type: SERVICE_TRS
  elementPosition: {}
  symbols:
    CHECKED_TRS_CP_UUID:
      attributes:
        id: CHECKED_TRS_CP_UUID
        label: CP Characteristic UUID
      type: String
    CHECKED_TRS_RX_UUID:
      attributes:
        id: CHECKED_TRS_RX_UUID
        label: RX Characteristic UUID
      type: String
    CHECKED_TRS_SERVICE_UUID:
      attributes:
        id: CHECKED_TRS_SERVICE_UUID
        label: Service UUID
      type: String
    CHECKED_TRS_TX_UUID:
      attributes:
        id: CHECKED_TRS_TX_UUID
        label: TX Characteristic UUID
      type: String
    TRS_CP_UUID:
      attributes:
        id: TRS_CP_UUID
        label: CP Characteristic UUID
      type: String
    TRS_ENABLE_CONFIG:
      attributes:
        id: TRS_ENABLE_CONFIG
        label: Enable Config
      children:
      - children:
        - attributes:
            id: SERVICE_TRS
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    TRS_RX_UUID:
      attributes:
        id: TRS_RX_UUID
        label: RX Characteristic UUID
      type: String
    TRS_SERVICE_UUID:
      attributes:
        id: TRS_SERVICE_UUID
        label: Service UUID
      type: String
    TRS_TX_UUID:
      attributes:
        id: TRS_TX_UUID
        label: TX Characteristic UUID
      type: String
  userData: {}
