/*******************************************************************************
* Copyright (C) 2025 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/


/*******************************************************************************
  Application BLE Source File

  Company:
    Microchip Technology Inc.

  File Name:
    app_ble.c

  Summary:
    This file contains the Application BLE implementation for this project.

  Description:
    This file contains the Application BLE implementation for this project.

  Note: 
    The code is automatically generated by MCC based on the GUI settings. The 
    user should not add code to this file to avoid conflicts.
 *******************************************************************************/

#include "app.h"
#include "osal/osal_freertos_extend.h"
#include "app_ble.h"
#include "app_ble_handler.h"














// *****************************************************************************
// *****************************************************************************
// Section: Macros
// *****************************************************************************
// *****************************************************************************


// *****************************************************************************
// *****************************************************************************
// Section: Global Variables
// *****************************************************************************
// *****************************************************************************

// *****************************************************************************
// *****************************************************************************
// Section: Function Prototypes
// *****************************************************************************
// *****************************************************************************


// *****************************************************************************
// *****************************************************************************
// Section: Functions
// *****************************************************************************
// *****************************************************************************

static void APP_BleStackCb(STACK_Event_T *p_stack)
{
    STACK_Event_T stackEvent;
    APP_Msg_T   appMsg;
    APP_Msg_T   *p_appMsg;

    (void)memcpy((uint8_t *)&stackEvent, (uint8_t *)p_stack, sizeof(STACK_Event_T));
    stackEvent.p_event=OSAL_Malloc(p_stack->evtLen);
    if(stackEvent.p_event==NULL)
    {
        return;
    }
    (void)memcpy(stackEvent.p_event, p_stack->p_event, p_stack->evtLen);
    stackEvent.p_event=stackEvent.p_event;

    if (p_stack->groupId==STACK_GRP_GATT)
    {
        GATT_Event_T *p_evtGatt = (GATT_Event_T *)stackEvent.p_event;

        if (p_evtGatt->eventId == GATTS_EVT_CLIENT_CCCDLIST_CHANGE)
        {
            uint8_t *p_payload;

            p_payload = (uint8_t *)OSAL_Malloc((p_evtGatt->eventField.onClientCccdListChange.numOfCccd*4));
            if (p_payload != NULL)
            {
                (void)memcpy(p_payload, (uint8_t *)p_evtGatt->eventField.onClientCccdListChange.p_cccdList, (p_evtGatt->eventField.onClientCccdListChange.numOfCccd*4));
                p_evtGatt->eventField.onClientCccdListChange.p_cccdList = (GATTS_CccdList_T *)p_payload;
            }
        }
    }

    appMsg.msgId=APP_MSG_BLE_STACK_EVT;

    ((STACK_Event_T *)appMsg.msgData)->groupId=p_stack->groupId;
    ((STACK_Event_T *)appMsg.msgData)->evtLen=p_stack->evtLen;
    ((STACK_Event_T *)appMsg.msgData)->p_event=stackEvent.p_event;

    p_appMsg = &appMsg;
    OSAL_QUEUE_Send(&appData.appQueue, p_appMsg, 0);
}

void APP_BleStackEvtHandler(STACK_Event_T *p_stackEvt)
{
    switch(p_stackEvt->groupId)
    {
        case STACK_GRP_BLE_GAP:
        {
            APP_BleGapEvtHandler((BLE_GAP_Event_T *)p_stackEvt->p_event);
        }
        break;

        case STACK_GRP_BLE_L2CAP:
        {
            APP_BleL2capEvtHandler((BLE_L2CAP_Event_T *)p_stackEvt->p_event);
        }
        break;

        case STACK_GRP_BLE_SMP:
        {
            APP_BleSmpEvtHandler((BLE_SMP_Event_T *)p_stackEvt->p_event);
        }
        break;

        case STACK_GRP_GATT:
        {
            APP_GattEvtHandler((GATT_Event_T *)p_stackEvt->p_event);
        }
        break;

        default:
        break;
    }

    //Direct event to BLE middleware
    BLE_DM_BleEventHandler(p_stackEvt);


    //Direct event to BLE profiles











    OSAL_Free(p_stackEvt->p_event);
}



static void APP_BleConfigBasic(void)
{
    int8_t                          connTxPower;
    BLE_GAP_LocalPrivacyParams_T    localPriParam;

    // Configure privacy
    localPriParam.privacyAddrType = CONFIG_BLE_GAP_PRIV_ADDR_TYPE;  /* Address Type */
    localPriParam.addrTimeout = CONFIG_BLE_GAP_PRIV_ADDR_TO;        /* Address Timeout */
    memset(localPriParam.localIrk, 0, 16);
    BLE_GAP_SetLocalPrivacy(true, &localPriParam);


    BLE_GAP_SetConnTxPowerLevel(CONFIG_BLE_GAP_CONN_TX_PWR, &connTxPower);      /* Connection TX Power */
}

static void APP_BleConfigAdvance(void)
{
    uint8_t devName[]=CONFIG_BLE_GAP_DEV_NAME_VALUE;
    int8_t selectedTxPower;
    BLE_GAP_ExtAdvParams_T advParams;
    uint8_t advData[]=CONFIG_BLE_GAP_EXT_ADV_DATA;
    BLE_GAP_ExtAdvDataParams_T appAdvData;
    int8_t selectedTxPower2;
    uint8_t advData2[]=CONFIG_BLE_GAP_EXT_ADV_DATA_2;

    BLE_SMP_Config_T                smpParam;

    BLE_DM_Config_T                 dmConfig;
    BLE_GAP_ServiceOption_T         gapServiceOptions;


    // Configure Device Name
    BLE_GAP_SetDeviceName(sizeof(devName), devName);    /* Device Name */

    //Configure advertising Set 1
    advParams.advHandle = CONFIG_BLE_GAP_EXT_ADV_ADV_SET_HANDLE;        /* Advertising Handle */
    advParams.evtProperies = CONFIG_BLE_GAP_EXT_ADV_EVT_PROPERTIES; /* Advertising Event Properties */
    advParams.priIntervalMin = CONFIG_BLE_GAP_EXT_ADV_PRI_INTERVAL_MIN;     /* Primary Advertising Interval Min */
    advParams.priIntervalMax = CONFIG_BLE_GAP_EXT_ADV_PRI_INTERVAL_MAX;     /* Primary Advertising Interval Max */
    advParams.priChannelMap = CONFIG_BLE_GAP_EXT_ADV_PRI_CHANNEL_MAP;       /* Primary Advertising Channel Map */
    memset(&advParams.peerAddr, 0x00, sizeof(advParams.peerAddr));
    advParams.filterPolicy = CONFIG_BLE_GAP_EXT_ADV_FILT_POLICY;    /* Advertising Filter Policy */
    advParams.txPower = CONFIG_BLE_GAP_EXT_ADV_TX_POWER;    /* Advertising TX Power */
    advParams.priPhy = CONFIG_BLE_GAP_EXT_ADV_PRI_ADV_PHY;      /* Primary Advertising PHY */
    advParams.secMaxSkip = CONFIG_BLE_GAP_EXT_ADV_MAX_SKIP;     /* Secondary Advertising Max Skip */
    advParams.secPhy = CONFIG_BLE_GAP_EXT_ADV_SEC_ADV_PHY;      /* Secondary Advertising PHY */
    advParams.sid = CONFIG_BLE_GAP_EXT_ADV_SID;     /* Advertising SID */
    advParams.scanReqNotifiEnable = CONFIG_BLE_GAP_EXT_ADV_SCAN_ENABLE;   /* Scan Request Notification Enable */
    advParams.priPhyOptions = CONFIG_BLE_GAP_EXT_ADV_PRI_ADV_PHY_OPT;  /* Primary Advertising PHY Option */
    advParams.secPhyOptions = CONFIG_BLE_GAP_EXT_ADV_SEC_ADV_PHY_OPT;  /* Secondary Advertising PHY Option */
    BLE_GAP_SetExtAdvParams(&advParams, &selectedTxPower);

    appAdvData.advHandle = CONFIG_BLE_GAP_EXT_ADV_ADV_SET_HANDLE;
    appAdvData.operation = BLE_GAP_EXT_ADV_DATA_OP_COMPLETE;
    appAdvData.fragPreference = BLE_GAP_EXT_ADV_DATA_FRAG_ALL;
    appAdvData.advLen = CONFIG_BLE_GAP_EXT_ADV_DATA_ORIG_LEN;
    appAdvData.p_advData=OSAL_Malloc(appAdvData.advLen);
    if(appAdvData.p_advData)
    {
        memcpy(appAdvData.p_advData, advData, appAdvData.advLen);       /* Advertising Data */
    }
    BLE_GAP_SetExtAdvData(&appAdvData);
    OSAL_Free(appAdvData.p_advData);
    

    //Configure advertising Set 2
    advParams.advHandle = CONFIG_BLE_GAP_EXT_ADV_ADV_SET_HANDLE_2;      /* Advertising Handle */
    advParams.evtProperies = CONFIG_BLE_GAP_EXT_ADV_EVT_PROPERTIES_2;   /* Advertising Event Properties */
    advParams.priIntervalMin = CONFIG_BLE_GAP_EXT_ADV_PRI_INTERVAL_MIN_2;   /* Primary Advertising Interval Min */
    advParams.priIntervalMax = CONFIG_BLE_GAP_EXT_ADV_PRI_INTERVAL_MAX_2;   /* Primary Advertising Interval Max */
    advParams.priChannelMap = CONFIG_BLE_GAP_EXT_ADV_PRI_CHANNEL_MAP_2;     /* Primary Advertising Channel Map */
    memset(&advParams.peerAddr, 0x00, sizeof(advParams.peerAddr));
    advParams.filterPolicy = CONFIG_BLE_GAP_EXT_ADV_FILT_POLICY_2;      /* Advertising Filter Policy */
    advParams.txPower = CONFIG_BLE_GAP_EXT_ADV_TX_POWER_2;      /* Advertising TX Power */
    advParams.priPhy = CONFIG_BLE_GAP_EXT_ADV_PRI_ADV_PHY_2;        /* Primary Advertising PHY */
    advParams.secMaxSkip = CONFIG_BLE_GAP_EXT_ADV_MAX_SKIP_2;       /* Secondary Advertising Max Skip */
    advParams.secPhy = CONFIG_BLE_GAP_EXT_ADV_SEC_ADV_PHY_2;        /* Secondary Advertising PHY */
    advParams.sid = CONFIG_BLE_GAP_EXT_ADV_SID_2;       /* Advertising SID */
    advParams.scanReqNotifiEnable = CONFIG_BLE_GAP_EXT_ADV_SCAN_ENABLE_2;     /* Scan Request Notification Enable */
    advParams.priPhyOptions = CONFIG_BLE_GAP_EXT_ADV_PRI_ADV_PHY_OPT_2;  /* Primary Advertising PHY Option */
    advParams.secPhyOptions = CONFIG_BLE_GAP_EXT_ADV_SEC_ADV_PHY_OPT_2;  /* Secondary Advertising PHY Option */
    BLE_GAP_SetExtAdvParams(&advParams, &selectedTxPower2);

    appAdvData.advHandle = CONFIG_BLE_GAP_EXT_ADV_ADV_SET_HANDLE_2;
    appAdvData.operation = BLE_GAP_EXT_ADV_DATA_OP_COMPLETE;
    appAdvData.fragPreference = BLE_GAP_EXT_ADV_DATA_FRAG_ALL;
    appAdvData.advLen = CONFIG_BLE_GAP_EXT_ADV_DATA_ORIG_LEN_2;
    appAdvData.p_advData=OSAL_Malloc(appAdvData.advLen);
    if(appAdvData.p_advData)
    {
        memcpy(appAdvData.p_advData, advData2, appAdvData.advLen);      /* Advertising Data */
    }
    BLE_GAP_SetExtAdvData(&appAdvData);
    OSAL_Free(appAdvData.p_advData);


    // GAP Service option
    gapServiceOptions.charDeviceName.enableWriteProperty = CONFIG_BLE_GAP_SVC_DEV_NAME_WRITE;             /* Enable Device Name Write Property */
    gapServiceOptions.charAppearance.appearance = CONFIG_BLE_GAP_SVC_APPEARANCE;                          /* Appearance */
    gapServiceOptions.charPeriPreferConnParam.enable = CONFIG_BLE_GAP_SVC_PERI_PRE_CP;                    /* Enable Peripheral Preferred Connection Parameters */
    gapServiceOptions.charEncDataKeyMatl.enable = CONFIG_BLE_GAP_SVC_ENC_DATA_KEY_MATL;                   /* Enable Encrypted Data Key Material */
    gapServiceOptions.charLeGattSecLvls.enable = CONFIG_BLE_GAP_SVC_LE_GATT_SEC_LVLS;                     /* Enable LE GATT Security Levels */
    BLE_GAP_ConfigureBuildInService(&gapServiceOptions);



    // Configure SMP parameters
    (void)memset(&smpParam, 0, sizeof(BLE_SMP_Config_T));
    smpParam.ioCapability = CONFIG_BLE_SMP_IOCAP_TYPE;                  /* IO Capability */
    smpParam.authReqFlag = CONFIG_BLE_SMP_OPTION;             /* Authentication Setting */

    BLE_SMP_Config(&smpParam);

    // Configure BLE_DM middleware parameters
    dmConfig.secAutoAccept = CONFIG_BLE_DM_SEC_AUTO_ACCEPT;                          /* Auto Accept Security Request */
    dmConfig.connConfig.autoReplyUpdateRequest = CONFIG_BLE_DM_AUTO_REPLY_UPD_REQ;      /* Auto Accept Connection Parameter Update Request */
    dmConfig.connConfig.minAcceptConnInterval = CONFIG_BLE_DM_MIN_CONN_INTERVAL;    /* Minimum Connection Interval */
    dmConfig.connConfig.maxAcceptConnInterval = CONFIG_BLE_DM_MAX_CONN_INTERVAL;    /* Maximum Connection Interval */
    dmConfig.connConfig.minAcceptPeripheralLatency = CONFIG_BLE_DM_MIN_CONN_LATENCY;    /* Minimum Connection Latency */
    dmConfig.connConfig.maxAcceptPeripheralLatency = CONFIG_BLE_DM_MAX_CONN_LATENCY;    /* Maximum Connection Latency */
    BLE_DM_Config(&dmConfig);


}

void APP_BleStackInitBasic(void)
{
    BLE_GAP_Init();

    BLE_GAP_AdvInit();  /* Advertising */

    BLE_GAP_ConnPeripheralInit();   /* Peripheral */

}

void APP_BleStackInitAdvance(void)
{
    uint16_t gattsInitParam=GATTS_CONFIG_NONE;


    STACK_EventRegister(APP_BleStackCb);


    BLE_GAP_ExtAdvInit();   /* Enable Extended Advertising */



    /* GAP (BLE_GAP_Init())shall be initialized before SMP */
    BLE_SMP_Init();

    /* GAP/SMP shall be initialized before L2CAP */
    BLE_L2CAP_Init();

    /* GAP/SMP/L2CAP shall be initialized before GATTS */
    GATTS_Init(gattsInitParam);



    //Initialize BLE middleware
    BLE_DM_Init();
    BLE_DM_EventRegister(APP_DmEvtHandler);



    //Initialize BLE services

    //Initialize BLE profiles












    APP_BleConfigAdvance();
}

void APP_BleStackInit(void)
{
    APP_BleStackInitBasic();
    APP_BleConfigBasic();
    APP_BleStackInitAdvance();
}